# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.11.21-25-gad4434f
_src_path: gh:scientific-python/cookie
backend: hatch
docs: sphinx
email: robbiand@umich.edu
full_name: Andrew Robbins
license: MIT
org: theAeon
project_name: prosperparser
project_short_description: A package for filtering the output of ProsperousPlus.
url: https://github.com/theAeon/prosperparser
vcs: true
